### ISSUE TITLE
Unnecessary string conversion of file path

### ISSUE THREAD

**Issue by chputnam** [forbjok/rust-codesign#1]
**SignTool::sign()** has an unnecessary string conversion of the **path** parameter which could result in a panic if the conversion fails.

**std::path::Path** implements **AsRef<OsStr>**, so you just need to get a view of the parameter as a **Path** using **AsRef<Path>::as_ref()**.

**Comment by chputnam** [comment]
I can't seem to open a PR, so here's the diff:

```
24,26d23
<         // Convert path to string reference, as we need to pass it as a commandline parameter to signtool
<         let path_str = path.as_ref().to_str().unwrap();
<
37c34
<         cmd.arg(path_str);
---
>         cmd.arg(path.as_ref());
```

**Comment by forbjok** [comment]
Done.
